#!/usr/bin/env bash

unameOut="$(uname -s)"
set -- $1
# echo "${1} and ${2}" >/tmp/test/stdout.log 2>/tmp/test/stderr.log
# echo "second_arg: $second_arg" >/tmp/test/stdout.log 2>/tmp/test/stderr.log
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac

if [[ "$machine" = "Mac" ]];then
    "${2}" /Users/"${1}"/.attendance/attendance.py "${1}" >/tmp/stdout.log 2>/tmp/stderr.log
else
    python3 /opt/attendance/attendance.py &> /opt/attendance/.attendance_status
fi
